### ISSUE TITLE
你好，没有配置文件吗

### ISSUE THREAD

**Issue by Tiantian20000321** [Enderfga/DoubleCheck#1]
你好，没有配置文件吗

**Comment by Enderfga** [comment]
有遇到什么问题吗，由于使用到的都是很常见的库，这里没有专门列出

**Comment by Tiantian20000321** [comment]
> 有遇到什么问题吗，由于使用到的都是很常见的库，这里没有专门列出

你好，请问是直接运行run.py吗，我这里显示缺失文件

**Comment by Enderfga** [comment]
https://github.com/649453932/Chinese-Text-Classification-Pytorch   可以参考这个仓库的内容

**Comment by Tiantian20000321** [comment]
> 有遇到什么问题吗，由于使用到的都是很常见的库，这里没有专门列出

<img width="1234" alt="图片1" src="https://github.com/Enderfga/DoubleCheck/assets/121372157/63ac2912-f27c-4eec-8e2f-8f774d80b083">

**Comment by Enderfga** [comment]
我们没有release预训练ckpt的计划，你可以从头开始训练

**Comment by Tiantian20000321** [comment]
> 我们没有release预训练ckpt的计划，你可以从头开始训练

好的，感谢回复，祝身体健康，工作顺利！

**Comment by Tiantian20000321** [comment]
> 我们没有release预训练ckpt的计划，你可以从头开始训练

你好，我想请问一下是怎么预训练的。

**Comment by Enderfga** [comment]
代码是基于https://github.com/649453932/Chinese-Text-Classification-Pytorch改写的 可以参考这里的说明

**Comment by Tiantian20000321** [comment]
> 代码是基于[https://github.com/649453932/Chinese-Text-Classification-Pytorch改写的](https://github.com/649453932/Chinese-Text-Classification-Pytorch%E6%94%B9%E5%86%99%E7%9A%84) 可以参考这里的说明

对sklearn版本有要求吗，我这里根据那个参考的跑还是报错了，那个metric有点问题，参考的也没有说明sklearn版本，我使用的是1.3.0

**Comment by Enderfga** [comment]
随着版本更新，原先的代码接口可能变动或者被删除。没有提供具体的报错信息，我也无法知道是什么问题。此外，如果您的报错信息涉及到某个特定的metric有问题，您可以尝试查阅sklearn官方文档或网上资源，寻找有关该metric的更多信息或解决方案。如果您在使用sklearn版本1.3.0仍然遇到问题，您也可以考虑尝试降级。
