### ISSUE TITLE
大哥大哥，代码是不是不全呀

### ISSUE THREAD

**Issue by Gaopayvin** [Enderfga/DoubleCheck#2]
BERT+GCN的代码没有呀，还有其他对比实验的模型，然后您论文的模型我好像也没有看到，能否解答一下谢谢！

**Comment by Enderfga** [comment]
[TextRNN_Att_new.py](https://github.com/Enderfga/DoubleCheck/blob/main/models/TextRNN_Att_new.py) is ours, I suggest you send an email to the first author of the paper asking for help. The part you inquired about was not completed by me.
